server:
  port: 9888
spring:
  application:
    name: scheduler
  quartz-datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://dev.feikongbao.cn:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dev
    password: Yodoo1sfaraway
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    #initialize-schema: embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            dataSource: quartz-datasource
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true